apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-replicas
  namespace: portfolio
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      name: myapp
  template:
    metadata:
      name: myapp
      labels:
        name: myapp
    spec:
      containers:
       - name: myapp
         image: achebeh/my-react-portfolio
         resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
         ports:
          - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  namespace: portfolio
spec:
  type: LoadBalancer
  selector:
    name: myapp
  ports:
  - port: 8080
    targetPort: 80