#!/usr/bin/env groovy
pipeline {
    agent any
    environment {
        AWS_ACCESS_KEY_ID = credentials('AWS_ACCESS_KEY_ID')
        AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
        AWS_DEFAULT_REGION = "us-east-1"
    }
    stages {
        stage("Create webapp namespace"){
            steps{
                script{
                    try{
                        sh "kubectl create namespace webapp"
                    }
                    catch(error){

                    }
                }
            }
        }
        stage("Deploy to web-App") {
            steps {
                script {
                    dir('web-app') {
                        try{
                            sh "aws eks update-kubeconfig --name project1ekscluster"
                            sh "kubectl create -k kubernetes"
                        }
                        catch(error){
                            sh "kubectl apply -k kubernetes"
                        }

                    }
                }
            }
        }
    }
}